spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: customer
          uri: lb:http://CUSTOMER
          predicates:
            - Path=/api/customers/**
        - id: bus
          uri: lb:http://BUS
          predicates:
            - Path=/api/buses/**


#Eureka Server Configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

server:
  port: 8092

